name: game_levels_scrolling_map
description: A package for making game levels map like candy crush or similar games using flutter with ability to be horizontal or vertical
version: 0.0.7
homepage: https://github.com/MohamedSayed9392/Game-Levels-Scrolling-Map

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
dependency_overrides:
  file: ^7.0.0
flutter:
